default_language_version:
  python: python3.8
repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: python
        files: \.py$
        args: [--config=pyproject.toml]
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8
        language: python
        files: \.py$
        args: [--config=.flake8]
-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: isort
        language: python
        files: \.py$
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy
        language: python
        files: \.py$
