[tool.black]
line-length = 119
exclude = '''
/(
  | migrations
)/
'''

[tool.isort]
profile = "black"
line_length = 119
skip_glob = "*/migrations/*.py"
known_django = "django"
known_first_party = "sporpa/"
sections = "FUTURE,STDLIB,THIRDPARTY,DJANGO,FIRSTPARTY,LOCALFOLDER"

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
ignore_missing_imports = true
exclude = [
    'local\.py$',
]

[tool.django-stubs]
django_settings_module = "sporpa"
