[tool.black]
line-length = 119
check = true
force-exclude = '''
/(
  | migrations
)/
'''

[tool.isort]
profile = "black"
line_length = 119
skip_glob = "*/migrations/*.py"
filter_files = true
known_django = "django"
known_first_party = "sporpa/"
sections = "FUTURE,STDLIB,THIRDPARTY,DJANGO,FIRSTPARTY,LOCALFOLDER"

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
ignore_missing_imports = true
disallow_untyped_defs = true
exclude = [
    'local\.py$',
]

[tool.django-stubs]
django_settings_module = "sporpa"

[tool.pytest.ini_options]
pythonpath = "sporpa"
DJANGO_SETTINGS_MODULE = "core.settings.test"
addopts = "--nomigrations --cov=. --cov-report=html"
