[tool.black]
line-length = 119

[tool.isort]
profile = "black"
line_length = 119
filter_files = true
known_django = "django"
known_first_party = "sporpa/"
sections = "FUTURE,STDLIB,THIRDPARTY,DJANGO,FIRSTPARTY,LOCALFOLDER"

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
ignore_missing_imports = true
disallow_untyped_defs = true
show_error_codes = true
disable_error_code = ["attr-defined"]
exclude = [
    'local\.py$',
]

[tool.django-stubs]
django_settings_module = "sporpa"

[tool.pytest.ini_options]
pythonpath = "sporpa"
DJANGO_SETTINGS_MODULE = "core.settings.test"
addopts = "--cov=. --cov-report=html"
