# Generated by Django 4.1.2 on 2022-11-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Unspecified"), (2, "Male"), (3, "Female")], default=1, verbose_name="gender"
            ),
        ),
    ]
