# Generated by Django 4.1.7 on 2023-04-08 10:52

from django.db import migrations, models

import accounts.models.user


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, upload_to=accounts.models.user.user_directory_path),
        ),
    ]
