# Generated by Django 4.1.5 on 2023-01-24 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_activity_available_between_at"),
        ("participants", "0002_alter_playersport_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipationRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("message", models.CharField(blank=True, max_length=250, verbose_name="message")),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participation_requests",
                        to="events.activity",
                        verbose_name="activity",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participation_requests",
                        to="participants.player",
                        verbose_name="participant",
                    ),
                ),
            ],
            options={
                "verbose_name": "participation request",
                "verbose_name_plural": "participation requests",
                "db_table": "participation_request",
            },
        ),
    ]
