# Generated by Django 4.1.5 on 2023-01-15 13:13

import django.contrib.postgres.fields.ranges
from django.db import migrations

import events.validators


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="available_between_at",
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(
                validators=[events.validators.validate_now_less_than_lower_value], verbose_name="available between at"
            ),
        ),
    ]
