# Generated by Django 4.1.2 on 2022-11-13 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("participants", "0001_initial"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityplayer",
            name="player_sport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="participants.playersport", verbose_name="player"
            ),
        ),
        migrations.AddField(
            model_name="activitylevel",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="events.activity", verbose_name="activity"
            ),
        ),
        migrations.AddField(
            model_name="activitylevel",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="participants.sportlevel", verbose_name="level"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="levels",
            field=models.ManyToManyField(
                related_name="activities",
                through="events.ActivityLevel",
                to="participants.sportlevel",
                verbose_name="level",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="player_sports",
            field=models.ManyToManyField(
                related_name="activities",
                through="events.ActivityPlayer",
                to="participants.playersport",
                verbose_name="player sport",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="sport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activities",
                to="participants.sport",
                verbose_name="sport",
            ),
        ),
        migrations.AddConstraint(
            model_name="activityplayer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_organizer", True)),
                fields=("activity", "is_organizer"),
                name="only_one_organizer",
            ),
        ),
        migrations.AddConstraint(
            model_name="activitylevel",
            constraint=models.UniqueConstraint(fields=("activity", "level"), name="activity_level_unique"),
        ),
    ]
