# Generated by Django 4.1.2 on 2022-12-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="activity",
            constraint=models.CheckConstraint(
                check=models.Q(("available_between_at__lower_inf", False)),
                name="lower_cannot_be_infinite",
                violation_error_message="available_between_at lower value cannot be infinite.",
            ),
        ),
        migrations.AddConstraint(
            model_name="activity",
            constraint=models.CheckConstraint(
                check=models.Q(("available_between_at__upper_inf", False)),
                name="upper_cannot_be_infinite",
                violation_error_message="available_between_at upper value cannot be infinite.",
            ),
        ),
    ]
