# Generated by Django 4.1.2 on 2022-12-17 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0002_alter_playersport_options"),
        ("events", "0003_activity_lower_and_upper_cannot_be_infinite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylevel",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_levels",
                to="events.activity",
                verbose_name="activity",
            ),
        ),
        migrations.AlterField(
            model_name="activitylevel",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_levels",
                to="participants.sportlevel",
                verbose_name="level",
            ),
        ),
        migrations.AlterField(
            model_name="activityplayer",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_players",
                to="events.activity",
                verbose_name="activity",
            ),
        ),
        migrations.AlterField(
            model_name="activityplayer",
            name="player_sport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_players",
                to="participants.playersport",
                verbose_name="player",
            ),
        ),
    ]
